---
- hosts: win
  vars_files:
          - secret.yml
  tasks:
          - setup:
            register: s
          - debug:
                  var: s
          - debug:
                  var: user
...
